### ISSUE TITLE
Audio not working - Clue Flow

### ISSUE THREAD

**Issue by naThnaabu** [playfultechnology/propcontrol#1]
For me the audio out is not working.
Filename is set and file is there.

Anyone an idea?

**Comment by naThnaabu** [comment]
Got the file working but its playing it in ui instead of the timer window

**Comment by alastaira** [comment]
If you look at the properties of the Audio Out node, you'll be able to assign it to a group. Make sure that the audio corresponds to a tab and group that matches the timer window, and it should play there.

**Comment by mrnelson03** [comment]
Is it possible to play a windows media playlist (or is there a playlist file that will work) in Node Red?
