### ISSUE TITLE
 Line break in UIBuilder

### ISSUE THREAD

**Issue by code1882** [playfultechnology/propcontrol#10]
I'm currently trying to create an in-room display for my escape room based on the Wiki posts.
I would like to give players a tip like:

Here is a
VERY VERY
helpful tip

Is there a way to format msg.clueText so that I can send a line-wrapped text to UIBuilder?

**Comment by alastaira** [comment]
Yes - you can send an HTML line break using the `<br/>` tag:
```Here is a<br/>VERY VERY<br/>helpful tip```
