### ISSUE TITLE
RFID ESP32

### ISSUE THREAD

**Issue by steuforia** [playfultechnology/propcontrol#12]
Hello there, 
Do you think you can make the same  propcontrol RFID for an ESP32?  i'm not coder and can't get it with chatgpt...

**Comment by alastaira** [comment]
I've added this example: https://github.com/playfultechnology/node-redscape/tree/master/ESP32/Wi-Fi/MQTT/PropControl_RFID

**Comment by steuforia** [comment]
thanks a lot mate, if you have a btc adresss let me know, would love to buy you a drink

**Comment by steuforia** [comment]
just found your patreon !
