### ISSUE TITLE
Node-redscape wont show timer/clue in uibuilder

### ISSUE THREAD

**Issue by jorisjacobs** [playfultechnology/propcontrol#2]
dear reader.

some months ago i was trolling around with this nice set of node-red codes.
we already had an escape room running node red, with custom made boards to suit our needs.

then i came acros this set. had a nice setup made ust to look if it is any better then what we had,
it was so much better then the current one running on right now.
then when i whas completely happy the sd card crashed ;(

i did try to set it up once again. though now the ui_builder displays wont show the timerText and clueText anymore...
its just showing up as 
{{msg.timerText}}
{{msg.clueText}} 

but not showing what the node are giving.

some help would be nice.

**Comment by dracedj** [comment]
Did you already find the solution?

**Comment by kornijow** [comment]
I actually used this in one of my rooms and it worked fine, but now I'm working of another one and have the same issue.

**Comment by LouisDeGuinness** [comment]
Did you install the packages because of the breaking changes of uibuilder like mentioned in https://github.com/playfultechnology/node-redscape/wiki?

> IMPORTANT NOTE: There was a breaking change introduced in version v3.1.3 of the uibuilder node (released Jan 2021), which means that you now need to manually install the vue libraries which Node-RedScape uses. To do, double-click to edit the properties of the uibuilder node in a flow, and open the front-end library manager. Then, under "Installed Packages", click the add+ icon and type the name of the following packages if they are not already installed:

    bootstrap-vue
    bootstrap
    jquery
    vue

**Be sure to choose "vue@v2-latest" because it doesn't work (at least for me) with vue v3**

**Comment by Earlfr** [comment]
I've got exactly the same issue... installing vue@v2-latest doesn't change anything :(
