### ISSUE TITLE
Typos on Video Overlay

### ISSUE THREAD

**Issue by EuanH2020** [playfultechnology/propcontrol#3]
Hi Alastair,

Just in case anyone else tries to use the Video Overlay flow I thought I'd feedback a few minor typos.

Flow:
Missing "[" at start.

index.html:
You get a warning about missing named entity but it refers to the ampersand in the link and doesn't seem to matter.

index.css:
Missing "body {"

Also if anyone else gets the issue that the uibuilder doesn't work. I had to upgrade node.js to latest version, update node-red, uninstall and reinstall uibuilder and uninstall and reinstall each of the front-end library packages (i.e. vue, boostrap, bootstrap-vue and jquery). Once I did that the problem resolved.

Thanks again for sharing the flow.

**Comment by nobasisstudios** [comment]
Here's the code with those corrections.

https://github.com/nobasisstudios/node-redscape-wiki/blob/master/Video-Overlay-(and-Video-Background).md

**Comment by alastaira** [comment]
Hi, thanks for these - there has been a note about the breaking change in uibuilder on the wiki page for some time, but I'm not sure people are looking there - they're just downloading the code! I'm planning a complete overhaul of the codebase imminently anyway.
