### ISSUE TITLE
Missing UI elements

### ISSUE THREAD

**Issue by jalakoo** [playfultechnology/propcontrol#7]
After importing all the core components, I get quite a few missing UI elements.  My understanding from this earlier [issues thread](https://github.com/playfultechnology/node-redscape/issues/5) (#5) is that we're supposed to build our own instances of these components using [UIBuilder](https://flows.nodered.org/node/node-red-contrib-uibuilder), is that correct?

![Screenshot 2023-03-21 at 4 54 30 PM](https://user-images.githubusercontent.com/960717/226767860-c1db4d3a-3a9f-449b-a04a-ab5f37e519d8.png)

**Comment by AshbyGeek** [comment]
I've actually found the answer to this, you just need to install the following pallets:
 - [node-red-dashboard](https://flows.nodered.org/node/node-red-dashboard)
 - [node-red-node-serialport](https://flows.nodered.org/node/node-red-node-serialport)
 - [node-red-contrib-uibuilder](https://flows.nodered.org/node/node-red-contrib-uibuilder#:~:text=uibuilder%20provides%20a%20stand%2Dalone,to%20create%20custom%20web%20interfaces.)

Edit: added more dependencies

**Comment by GercovanStraten** [comment]
Strange, I have both of these pallets installed, but still missing those uibuilder elements.
Any ideas on a solution (or other missing palette) for this?
Thanks!

EDIT: Oops, just needed one more minute of looking around in the wiki ;-)
Found the answer here: https://github.com/playfultechnology/node-redscape/wiki/Creating-a-full-screen-in-game-display

**Comment by AshbyGeek** [comment]
Oh, haha. I forgot to list that because I followed that wiki page before trying to import any of his flows. I'll add it to my first post
